#!/usr/bin/bash

echo "enter filename"
read  filname

echo "#include<stdio.h>
#include <stdlib.h>

/**
 * main - printing from a to z lowercase
 *
 * Return: Always 0 (Sucess)
 */" > ${filname}
vi ${filname}
